<?php

/**
 * @file
 * Contains gel.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function gel_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the gel module.
    case 'help.page.gel':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Gel Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function gel_theme() {
  return [
    'gel' => [
      'render element' => 'children',
    ],
  ];
}
